name: Node.js CI

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm test

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js for Backend
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Backend Dependencies
      working-directory: ./blog-backend
      run: npm install

    - name: Start Backend
      working-directory: ./blog-backend
      run: npm start &

    - name: Wait for Backend to Start
      run: sleep 15 # Adjust time if needed

    - name: Run Backend Tests
      working-directory: ./blog-backend
      run: npm run test

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Frontend Dependencies
      working-directory: ./blog-frontend
      run: npm install

    - name: Start Frontend
      working-directory: ./blog-frontend
      run: npm start &

    - name: Wait for Frontend to Start
      run: sleep 15 # Adjust time if needed

    - name: Run Cypress Tests
      working-directory: ./blog-frontend
      run: npm run cy:run

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: [build, backend-tests, frontend-tests]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

    - name: Build Project
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

    - name: Deploy to Vercel
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
