name: Node.js CI

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install

  start-services:
    name: Start Backend and Frontend Services and test it
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for Backend and Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        working-directory: ./blog-backend
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: ./blog-frontend
        run: npm install

      - name: Start Backend
        working-directory: ./blog-backend
        run: |
          npx kill-port 3000
          npm start &
        env:
          PORT: 3000

      - name: Start Frontend
        working-directory: ./blog-frontend
        run: |
          npx kill-port 3001
          npm start &
        env:
          PORT: 3001

      - name: Wait for Backend and Frontend to Start
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3000; then
              echo "Backend is up"
              break
            fi
            echo "Waiting for Backend to start..."
            sleep 5
          done
          for i in {1..30}; do
            if curl -s http://localhost:3001; then
              echo "Frontend is up"
              break
            fi
            echo "Waiting for Frontend to start..."
            sleep 5
          done


      - name: Run Cypress Tests - Frontend
        working-directory: ./blog-frontend
        run: npm run cy:run -- --headless
        
      - name: Run Cypress Tests - Backend
        working-directory: ./blog-backend
        run: npm run test -- --headless   

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
